### ISSUE TITLE
Build fails, wiki outdated

### ISSUE THREAD

**Issue by Hoimar** [Pyramid-Apex-Games/Polyhedron#8]
After goind through the hassle of getting the dependencies…

- building and installing an up to date cmake
- installing all kinds of packages, some of which are listed in the wiki
- installing python3 pip (pip3), then pip3 install clang

I could create the make files.
But `cmake --build .` fails with

> Traceback (most recent call last):
>   File "<folder>/src/binding/index.py", line 129, in <module>
>     generate_code(args[1], args[2])
>   File "<folder>/src/binding/index.py", line 58, in generate_code
>     parser = CppParser(CompileCommandsFolder, file)
>   File "<folder>/src/binding/autobind/parsecpp.py", line 29, in __init__
>     self.flags = CompileFlagsFor(buildfolder, file)
>   File "<folder>/src/binding/autobind/compileflags.py", line 17, in CompileFlagsFor
>     InitializeCompileCommands(buildpath)
>   File "<folder>/src/binding/autobind/compileflags.py", line 14, in InitializeCompileCommands
>     raise Exception("Invalid buildpath: {} not found in: {}".format(compile_commands_filename, buildpath))
> Exception: Invalid buildpath: compile_commands.json not found in: build
> CMakeFiles/Polyhedron.dir/build.make:316: recipe for target 'game+entities+player.binding.cpp' failed
> make[2]: *** [game+entities+player.binding.cpp] Error 1
> 

Wiki page: [https://github.com/Pyramid-Apex-Games/Polyhedron/wiki/Compiling](https://github.com/Pyramid-Apex-Games/Polyhedron/wiki/Compiling)

**Comment by WatIsDeze** [comment]
For now, since @Micha0 knows more about this. You can try and install VS:Code https://code.visualstudio.com/docs/languages/cpp 

Then add the folder with CMakeLists.txt to the workspace, and ctrl + p clean rebuild.
We're using this IDE and I can tell it is being a bit messy about what obviously is VS:Code related.

I'll have to excuse you for this one.

**Comment by Micha0** [comment]
know issue, should be fixed soon

**Comment by WatIsDeze** [comment]
Interesting that the rt was still missing. It shouldn't have been.

**Comment by WatIsDeze** [comment]
Updated the list of packages to be installed. Things to look for @Micha0  is that python3 pip will install clang6 so it seems. 

And most notably, it seems we should rewrite the entire wiki page since as you stated it'll only work with make and ninja generators. Best just tell folks to use ccmake and cmake for this project instead.

Anyone with a solution is free to advise.

**Comment by Micha0** [comment]
So, the only way to reliably solve this, was by actually regenerating the project for Makefiles or Ninja, which kinda defeats the purpose. Therefore, if you want to use anything else than Ninja or Makefiles, make sure you generate one of those and copy the `compile_commands.json` file over to your non-makefile/ninja build folder. 
The auto script binding will know give a more informative error message explaining this. I consider this one solved.
Thank you, and good night!
